export const LOGIN = "LOGIN"
export const USERDETAILS = "USERDETAILS"
export const UPDATESTORE = "UPDATESTORE"
export const RETURNUSER = "RETURNUSER"
export const RESUMESITE = "http://localhost:8090/"
